### ISSUE TITLE
SSW Silent Failure

### ISSUE THREAD

**Issue by bcompter** [Solaris-Skunk-Werks/solarisskunkwerks#1]
SSW will fail silently if it can't find data files such as patterns.zip.  It should show an error message of some kind and indicate to the user what the problem is.

**Comment by WEKarnesky** [comment]
Solaris-Skunk-Werks/battletech-force-balancer Also has this issue.

**Comment by Algebro7** [comment]
This is fixed by https://github.com/Solaris-Skunk-Werks/sswlib/commit/22502291ba173cbc85d3a53d1c9c31ee2c98b38e (caca838)
