### ISSUE TITLE
Option to remove GYRO when using INTERFACE COCKPIT

### ISSUE THREAD

**Issue by Nehvar** [Solaris-Skunk-Werks/solarisskunkwerks#104]
If you select an **INTERFACE COCKPIT** during 'Mech construction you have the option to construct it without a **GYRO**.

Source: _Interstellar Operations_ p.116

"A BattleMech with an interface cockpit may be constructed without
a gyro, in which case the usual Gyro slots on the unit’s Critical Hit Table
are treated as empty, and can be used for other components."

Edit: Changed "Imaging" to "Interface" in the title/comment.  I mixed the name up with the Enhanced Imaging cockpit system from MaxTech, sorry.

**Comment by WEKarnesky** [comment]
Looks like this is there, but not in Dark age era, only Clan invasion.  

![image](https://user-images.githubusercontent.com/8506084/71564688-ba0b9a80-2a59-11ea-9308-97626b6a91ce.png)

The availability code for No Gyro seems to confirm this, which makes this a bug, not an enhancement.

![image](https://user-images.githubusercontent.com/8506084/71564695-da3b5980-2a59-11ea-95e7-84ca0bfd2922.png)

**Comment by Nehvar** [comment]
Oh, I completely missed that the option was available at all when the Tech Base is set to Inner Sphere (or Mixed, it seems).  Sorry about that.

In that case I'd like to add to the bug report that the "No Gyro" option is also missing from **Tech Base: Clan** for both **Clan Invasion and Dark Ages** periods.

I'm completely new here so I don't know how you prefer to do things.  Please let me know if you would rather I post the above in a new issue than add it here.

**Comment by WEKarnesky** [comment]
> I'm completely new here so I don't know how you prefer to do things. Please let me know if you would rather I post the above in a new issue than add it here.

It's fine.  I'll go in and make sure the "No Gyro" option has the same availability as the Interface Cockpit.

**Comment by WEKarnesky** [comment]
Released in 0.7.3.20191031 Nightly
