### ISSUE TITLE
[SSW] Weapons with more than 7 crits can not be added to a turret.

### ISSUE THREAD

**Issue by Nehvar** [Solaris-Skunk-Werks/solarisskunkwerks#106]
I ran into this bug while while trying to mount a Clan RAC5 in a Marauder shoulder turret.  After some experimentation it seems that SSW won't allow any weapon with more than seven crits to be mounted in a turret (Clan or IS).  I looked through the TechManual, TO, SO, IO and their respective erratas but I cannot find any restrictions to the turrets beyond /_must fit in location with turret_/ and /_no heavy gauss allowed_/.  So I'm reasonably sure this is a bug.

**Comment by WEKarnesky** [comment]
I fixed this last night but did not have time to push out a nightly release.  When I have time I will do so, then close this.

**Comment by WEKarnesky** [comment]
This is released in https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/releases/tag/0.7.3.20200113
