### ISSUE TITLE
cannot find patterns.zip at path specified on launch

### ISSUE THREAD

**Issue by PharohBeer** [Solaris-Skunk-Werks/solarisskunkwerks#116]
**Describe the bug**
have confirmed SSW 0.7.20200113 contains all files needed as downloaded (including patterns.zip in question), upon opening program I receive error message "Error: could not find file: .\Data\Printing\patters.zip (The system cannot find the path specified)"
**To Reproduce**
1. Open cmd, type usual launch text 'java -jar ' and drag SSW.jar from file explorer into cmd window, enter command.
2. see initial memory allocated message, in my case 'Memory Allocated [7589068]'
3. see SSW splash loading screen, receive error message. After memory allocated msg no further cmd output, after exiting error message application persists until cmd is closed

**Expected behavior**
upon running SSW, application continues loading and finds patterns.zip in question. launches application.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Microsoft Windows Version 1809, OS Build 17763.1039
 - Browser: Chrome
 - Version: SSW Build 0.7.20200113, Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Additional context**
Currently have WinRAR installed, Version 5.80 1 beta 40 day trial (my preferred unzip tool), may be confounding factor in java efforts to unzip files.

**Comment by WEKarnesky** [comment]
User was not navigating to install directory.  Future users encountering this problem can solve it by:

1: open windows explorer
2: navigate to the root of your SSW installation
3: go up one directory
4: hold Shift and right click on the SSW folder
5: select "Open Powershell window here" or "Open command window here"
6: in new cmd window that opens run `java -jar SSW.jar`

Alternatively, having Java in your path and assigning JARs as executable in the windows environment will also solve this.
