### ISSUE TITLE
SAW - Heavy Flamers are requiring heat sinks and power amps

### ISSUE THREAD

**Issue by Maelwys** [Solaris-Skunk-Werks/solarisskunkwerks#128]
And they shouldn't. Since they're an ammo-based flamer, they shouldn't require heat sinks and amplifiers, Atleast as far as I can tell. TechManually specifically spells this out for vehicle flamers (page 218), but TO doesn't specifically state this as far as I can tell. 

However, the Bolla Stealth Tank Dominus has a heavy flamer, and isn't requiring heat sinks, so...

The heavy flamer is working correctly when it comes to not needing power amps when there's a fusion engine.

So this might be a simple switch in the equipment file.

**Comment by Algebro7** [comment]
Closed via #128
