### ISSUE TITLE
SAW BV issue

### ISSUE THREAD

**Issue by Maelwys** [Solaris-Skunk-Werks/solarisskunkwerks#130]
- [ ] WiGE Defensive Factor

- [ ] Armor Type Modifier

**WiGE Defensive Factor** 
As far as I can tell, and someone should check, SAW is not taking into account the WiGE's inherent +1 TMM when calculating its Defensive Factor.

So a WiGE normally has a +3 modifier for moving 8 hexes, it gets +1 for being a WiGE (like a VTOL), so its Defensive Factor should be 1.4. Right now its using 1.3.

Shouldn't be too much of an issue, VTOLs are handling it correctly at the moment.

**Armor Type Modifier**
The formula for calculating the BV of armor in a Combat Vehicle is Armor Factor (Points) x Armor Type Modifier x 2.5.

Right now, SAW seems to be just doing Armor Factor x 2.5, and not including the Armor Type Modifier.

However, in the Cost/BV Breakdown page, it is displaying it properly as seen in the following example from the Narukami
"Total Armor Factor (140) * Armor Type Modifier (2.0) * 2.5                350.00"

So SAW knows about the Armor Type modifier, and puts in the BV page, but doesn't actually put it into the calculation, so it should be a relatively simple fix.

**Comment by Maelwys** [comment]
Make sure we double check this one. I'm pretty sure its not working as intended, but who knows.

**Comment by Algebro7** [comment]
Here's a build for @Maelwys to test:

[SSW_0.7.4 RC2.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/5180737/SSW_0.7.4.RC2.zip)

@WEKarnesky would you prefer to squeeze this into 7.4 or merge into develop instead?

**Comment by Algebro7** [comment]
Fixed via #161
