### ISSUE TITLE
SAW GUI Issues

### ISSUE THREAD

**Issue by Maelwys** [Solaris-Skunk-Werks/solarisskunkwerks#134]
[] "Selected Variant" box doesn't clear when you load another vehicle or start a new vehicle.
[] "Lock Chassis" Button isn't always greyed out
[] Preferences don't seem to matter.

**Selected Variant** This is pretty self explanatory. If you load/create an OmniVehicle, and then start a new one, rather than clearing out, whatever variant you were looking at in SAW remains in the dropdown (which is greyed out so it isn't active).

**Lock Chassis** - This one is odder. When you start SAW, the Lock Chassis button is greyed out.  However, as soon load a design, then the button is no longer greyed out. Also if the button isn't greyed out, when you start a new design, it will stay active.

**Preferences** - The preferences window has been basically cribbed from SSW, and so has lots of options that don't make sense and needs to be cleaned up. However, the part that is applicable to SAW, the "New `Mech Defaults" don't seem to work at all. You can save them and so they're set, but they aren't applied when you start a new mech.

**Comment by gblouin** [comment]
@Maelwys can you post an update with what is still outstanding on this (or if it's been completed)?  Thanks!
