### ISSUE TITLE
SAW not counting Ammo when it comes to spaces

### ISSUE THREAD

**Issue by Maelwys** [Solaris-Skunk-Werks/solarisskunkwerks#137]
So Combat Vehicles are pretty easy when it comes to items. A vehicle has a number of spaces equal to 5 + (vehicle weight/5) (Round down). So a 10 ton vehicle has 7 spaces. Most items just take up one space. Ammo also takes up one space.

Page 107 TM
"Each ammo bin occupies one item slot, but may be of any weight desired, so long as the ammunition is devoted to one or more of the vehicle's weapons of the same type (for example, a vehicle with 3 AC/5s may store all AC/5 ammunition in a single bin of any size). All ammunition is presumed to have a body location."

Right now, SAW doesn't seem to dedicated any spaces to the ammo bins.

So to fix it, we need to assign spaces to ammo, but only one of each type. So 64 rounds of LRM15 ammo would only be a single space used up. 300 rounds of MG would be a single slot etc.

Of course, that does raise a question. If you have a LB2-X and you have a ton of Cluster Ammo and a ton of Slug ammo, is that 2 spaces, one for each type of ammo,or just one, since its just LB2-X ammo...

**Comment by Algebro7** [comment]
Should be fixed by 03bbd77
