### ISSUE TITLE
SSW BV Issues

### ISSUE THREAD

**Issue by Maelwys** [Solaris-Skunk-Werks/solarisskunkwerks#138]
* [ ] Streak LRMs

**Streak LRMs**
Streak LRMs (And probably iATMs as well, since they act as Streaks, but the Streak LRMs atleast) should act in the same manner that Streak SRMs when it comes to BVs. When calculating Offensive BVs, Streaks count as half heat when calculating what weapon battle values are modified.

https://discordapp.com/channels/598176054015950852/598176054766600234/700405589884272781

**Comment by Algebro7** [comment]
This should be fixed with 5a17594, please reopen if you see any further issues
