### ISSUE TITLE
[SSW]

### ISSUE THREAD

**Issue by Maelwys** [Solaris-Skunk-Werks/solarisskunkwerks#151]
According to IO (page 123) Primitive BattleMechs may

"Install Engine: Both Primitive BattleMechs and Primitive IndustrialMechs can use ICE, fuel cell, fission, or standard fusion engine types. " Meaning they can use the primitive versions of those 4 engines.

Right now SSW is restricting the Primitive BattleMechs to just the Primitive Standard Engine.

On the plus side, the Primitive IndustrialMech is working as intended and has access to those 4 engines, so it shouldn't need any major coding, just allowing the primitive BM to use them?

**Comment by Algebro7** [comment]
This should be fixed in #152
