### ISSUE TITLE
Unable to add a Mech Image to a printed record sheet

### ISSUE THREAD

**Issue by BowtieBob** [Solaris-Skunk-Werks/solarisskunkwerks#153]
**Describe the bug**
No mech image is added to the printed record sheet after checking the option to "Print Mech" and selecting an image file

**To Reproduce**
1. Go to 'Print Current Mech'
2. Click on 'Print Mech' checkbox
3. Click on 'Choose Image'
4. Select JPG file from local hard drive
5. Click on 'Print'
6. No image is added to the printed record sheet

**Expected behavior**
I expect to see the selected image appear in the blank space below the "Mechwarrior Data" section

**Desktop (please complete the following information):**
 - OS: Windows 10
 - SSW: 0.7.3.20191024

**Comment by Algebro7** [comment]
This was fixed in the [last dev release](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/releases/download/0.7.3.202000413/SSW_0.7.3.20200413.zip). Please try that and let me know if you have any other issues.
