### ISSUE TITLE
SSW: Remove commas from "Source" field automatically

### ISSUE THREAD

**Issue by mbear75** [Solaris-Skunk-Werks/solarisskunkwerks#155]
If I include a comma in the name of a product in the "Source" field, it breaks the layout of the index.ssi file and prevents the "Open"/"Select Mech" dialog box from populating.

Example problem entry: Recognition Guide: ilClan, Vol. 1

**Describe the solution you'd like**
**Describe alternatives you've considered**
Option 1: Have SSW parse the Source field value and automatically replace/remove any commas it finds.
Option 2: Maybe add a warning not to use commas?
Option 3: mbear should be less anal-retentive about punctuation.

**Additional context**
Discovered the issue when I found that deleting the SSI file would allow SSW to run once, and then when closed the problem would return.

**Comment by Algebro7** [comment]
index.ssi is essentially a comma-delimited CSV file, so option 1 won't really work, and 2 and 3 aren't ideal. 

Is source the only field ever likely to include a comma? If so, we can update the `Write()` method to escape or sanitize commas in that field.

**Comment by Algebro7** [comment]
Actually, we can probably just quote that field, which is what we should be doing anyway

**Comment by Algebro7** [comment]
We took another look at this and decided it would be best to overhaul the unitlist cache code. It won't be in the upcoming stable release but it should be in the next dev/nightly build. 

The new approach will allow any character you want in any of the string fields, so it should be more robust.

**Comment by mbear75** [comment]
I'm going to try to avoid commas. I thought I should report it though since the SSI file is a CSV, and I didn't want a [Bobby Tables](https://xkcd.com/327/) problem.

Thanks for looking at it so quickly!

**Comment by Algebro7** [comment]
I have been experimenting with a few different formats, and JSON is under consideration. JSON is somewhat slow and inefficient (in terms of file size) but the implementation is far simpler than what I was looking at (safe raw object serialization via Kryo).

**Comment by Algebro7** [comment]
Fixed via #173 , keep an eye out for the next dev release
