### ISSUE TITLE
[SSW] Wrong BV for Extended Fuel Tank

### ISSUE THREAD

**Issue by Maelwys** [Solaris-Skunk-Werks/solarisskunkwerks#158]
Currently the Extended Fuel Tank is being treated as an explosive piece of equipment (-1 to BV per critical slot).

However, it should be treated as ammo for purposes of BV (-15 per critical slot).

https://bg.battletech.com/forums/index.php?topic=67275.0

Basically part of the problem is the the .jsons have a spot for the equipment to be listed as explosive, but that kicks in the generic -1 BV per slot that all other equipment has, and there's no way to say 'do -15 instead.

**Comment by Algebro7** [comment]
Closed via #175
