### ISSUE TITLE
[SAW] "Limited amphibious" checkbox does not update when a vehicle is loaded

### ISSUE THREAD

**Issue by hagane** [Solaris-Skunk-Werks/solarisskunkwerks#160]
When opening a vehicle with a `Limited Amphibious` chassis mod the corresponding checkbox stays unchecked.

How to reproduce:
1. Run SAW
2. Load a vehicle with a limited amphibious mod enabled.

**Comment by Algebro7** [comment]
Should be fixed via #177, please let us know if you notice any more issues.
