### ISSUE TITLE
HarJels!

### ISSUE THREAD

**Issue by Maelwys** [Solaris-Skunk-Werks/solarisskunkwerks#164]
I believe I have everything done except possibly for the exceptions for the armor issues, but I'm not sure if those can be coded to the .json.

**HarJel**
Construction
Mechs
- [x] SSW Won't let you add HarJel if you have certain types of armor. This isn't a rule, but may be a unintended side effect of the (correct) restrictions in place for HarJel2 and HarJel3
- [x] Can only have one in each location

- [x] Cannot be Pod mounted on Omnis

Vehicles
- [x] Can only have one per locaton

BFB/AlphaStrike
- [x] Mechs gains the corresponding ability (BHJ) if it mounts the equipment in the Right, Left AND Center torso
- [x] Vehicles (Unknown at this time)

**HarJel II, HarJel III**
Mechs
- [ ] Construction - Can't add if you have the wrong armor, but can add wrong armor afterwards. Need to add exception for each armor type?
- [x] Only one per location
- [x] Cannot be pod mounted on Omnis

Vehicles
- [x] Can't use

BFB/AlphaStrike
- [x] Mechs gains the corresponding ability (BHJ2/BHJ3) if it mounts the equipment in the Right, Left AND Center torso
- [x] Vehicles - Can't use

Battle Value
- [x] Each HarJel II or HarJel III provides an additional BV modifier for the armor in any location where a HarJel II or III is mounted. HarJel II is a 1.1 modifier, HarJel III is a 1.2 modifier. This is in addition to any multipliers already in place (So if there's a 1.2 modifier and you add HarJel II, then it becomes 1.2x1.1 for a 1.32 armor modifier for the armor in that location.
- [x] Further Battle Value computations is taken care of already in the .json.

**Comment by Algebro7** [comment]
Here's a build for testing with the marked boxes above implemented...please check to make sure I haven't broken anything so far :) 

[SSW_0.7.4.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/5228917/SSW_0.7.4.zip)

**Comment by Algebro7** [comment]
One final build for testing before I open a PR for this:

[SSW_0.7.4.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/5240690/SSW_0.7.4.zip)

**Comment by Algebro7** [comment]
Closed via #169 , although we will need to fix the validation issue where you can add illegal armor later after some refactoring
