### ISSUE TITLE
Triple-strength myomer

### ISSUE THREAD

**Issue by Belgrath** [Solaris-Skunk-Werks/solarisskunkwerks#193]
**Describe the bug**
SSW is add 1 to the walk speed and not 2 
[9.pdf](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/5331278/9.pdf)

https://www.sarna.net/wiki/Triple_Strength_Myomer
From 35101 - Classic Battletech Total Warfare.pdf
• Increase the ’Mech’s Walking MP by 2 and recalculate
its Running MP; multiply the new Walking MP by 1.5,
rounding up. Triple-strength myomer does not affect
Jumping MP

**To Reproduce**
0. Open SSW
1. Go to File, Select New Mech
2. At the bottom left of the select TSM in the Enhancements drop down
3. Print Mech sheet 

**Expected behavior**
It should show 2 added to walk  (+2)
**Screenshots**
https://onedrive.live.com/embed?cid=2CFCB991FCAADCBD&resid=2CFCB991FCAADCBD%21757&authkey=ANJufbwdstr2uaI&em=2

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox 86.20b7
 - Version SSW 0.7.4

**Smartphone (please complete the following information):**
Nope
**Additional context**
Can we get large screen support?

**Comment by WEKarnesky** [comment]
I am pretty sure this is actually correct behavior.  While it is true that TSM ads 2 to the walking speed, it only activates at 9 heat when it also has a -1 to movement from the 5 heat penalty.

The two combine and so at 9 heat when the TSM activates it adds 1 net walk.

----

For the scaling try this:

Find java.exe you installed.
Right click -> Properties
Go to Compatibility tab
Check Override high DPI scaling behavior.
Choose System for Scaling performed by:

**Comment by Maelwys** [comment]
Right. Its a little oddly worded, but as shown by all the example RS from CGL, its a net +1 benefit

Page 143 of TW states

"Triple-strength myomer provides a benefit only when a BattleMech is running hot. If a BattleMech is equipped with triple-strength myomer, for each turn that it ends with a heat level of 9 or higher, the following effects take place the next turn; **apply other modifiers that decrease movement, such as heat and damage, normally**"

**Comment by WEKarnesky** [comment]
I think this issue can safely be closed.
