### ISSUE TITLE
Clan PPC Capacitors

### ISSUE THREAD

**Issue by Maelwys** [Solaris-Skunk-Werks/solarisskunkwerks#201]
Clantech PPC Capacitors are currently missing from SSW.

While TacOps introduced IS PPC Capacitors, IO told us the Clans developed them as well.

Unfortunately this isn't something that can be done via the equipment files because of how the capacitors are coded.

So we need to changes Capacitors from IS only to both, with the same availability as the IS Version (XXED) and a Clan intro date of 3101. There's no specific introduction faction.

**Comment by WEKarnesky** [comment]
Commit https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/commit/aa5cfd91ae1842f1c9dde553b85882453fc01f7f fixes this I believe.  Please re-open if you find it does not.
