### ISSUE TITLE
Unable to Find SSW.Master.zip

### ISSUE THREAD

**Issue by PedroAsani** [Solaris-Skunk-Werks/solarisskunkwerks#205]
I can't find the ssw.master.zip which is said to contain the "cannon" units (canon) on the releases page? Has it been rolled into the 0.7.4.1 release? If so, wiki needs updating. If not, then a clear link to the file would be helpful.

**Comment by Algebro7** [comment]
The SSW master units can be downloaded from https://github.com/Solaris-Skunk-Werks/SSW-Master. I agree it would be good to update the documentation to more clearly indicate this.

As for bundling it with SSW, I am not familiar with the details but I believe there was originally some licensing issue that prevented distributing them directly with the program. I am not sure if anything has changed regarding that but @WEKarnesky or @Maelwys might know more.

**Comment by WEKarnesky** [comment]
I second the documentation, and we will try to remember to upload a snapshot of the master file wither ever major release (we normally do that, just happened to forget this time).

  You can always download the latest at https://github.com/Solaris-Skunk-Werks/SSW-Master though you may need to delete the `README.md` after downloading, I haven't tested that recently.
