### ISSUE TITLE
TSM modification of sword's damage not included in BV calculation

### ISSUE THREAD

**Issue by JstnB** [Solaris-Skunk-Werks/solarisskunkwerks#210]
**Describe the bug**
A sword's damage is affected by triple-strength myomer, but the increased sword damage from using TSM is not included in the BV calculation.

For an example, see the SP2-X Spatha, which is shown in SSW as having a BV of 1953, while the MUL lists its BV (correctly) as 1973. The discrepancy seems to come from not doubling the sword's damage due to the TSM.

**Comment by WEKarnesky** [comment]
This is fixed in PR: #197 tsm melee bv fix and will be released soon.  Prerelease versions with it incorporated are available at https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/actions
