### ISSUE TITLE
Bulk SSW to MTF Converter

### ISSUE THREAD

**Issue by CampaignAnon** [Solaris-Skunk-Werks/solarisskunkwerks#216]
Other SSW Users and I would like to have an SSW to MTF converter that is capable of converting files in bulk, rather than individually loading each unit and exporting them. I know that for large directories (such as my 4000 customs), that's a time consuming process.

**Comment by WEKarnesky** [comment]
This was duplicated in ticket #217 and the reporter had the following to say:

> **Is your feature request related to a problem? Please describe.**
Yes, I godam hate doing this one file at a time

> **Describe the solution you'd like**
Can I make a feature request? I have always found the mass bulk converter in SSW that converts whole directories of HMP files to SSW files. Can someone please make a mass bulk converter of SSW files directories into MTF files directories? 

> **Describe alternatives you've considered**
see 1,  I godam hate doing this conversion from one SSW file to one MTF file one at a time.

> **Additional context**
Nope
