### ISSUE TITLE
UI issue makes it possible to create an introductory battlemech with industrial structure and I.C.E engine

### ISSUE THREAD

**Issue by Algebro7** [Solaris-Skunk-Werks/solarisskunkwerks#22]
*Reported by Templar Ken on Discord*
*Imported from https://github.com/WEKarnesky/solarisskunkwerks/issues/15*

**Describe the bug**
By configuring a mech loadout in a specific order, it's possible to create an introductory battlemech with industrial structure and an I.C.E engine, which should not ordinarily be possible.

**To Reproduce**
1. Open SSW and start a blank loadout
2. Set Mech Type to Industrial
3. Set Engine type to I.C.E Engine
4. Set Motive Type to Quad
5. Set rules level from Tournament Legal to Introductory
6. Click through warning prompt
7. Change motive type to biped

**Expected behavior**
The Chassis information associated with Industrial mechs should not be accepted when the "Mech Type:" Dialogue box reads "Battlemech".

**Additional context**
It seems a number of problems arise when the "Rules level" change whilst modifying the mech. For example I can change the Era, Tech Base, and Prod Year/Era under basic information; Change any of the Chassis then revert to an introductory Rules level and have all the changes stay.

This can lead to some weird stuff like having a Introductory level Clan Battlemech from the Clan invasion era with a Industrial mech type, Industrial structure, quad motive type, and a  I.C.E. engine.

**Comment by WEKarnesky** [comment]
It appears that in the most recent build (Post inclusion of DA availability) the Internal Structure and Fusion engine now resets. @Algebro7 Can you confirm if this is still an issue?

**Comment by Algebro7** [comment]
I cannot replicate either, although I'm not sure why this would've changed. Closing for now and will re-open if this resurfaces.
