### ISSUE TITLE
Ammunition showing as 0 Ammo and 0.0 Tonnage in 7.4 and beyond

### ISSUE THREAD

**Issue by S2000Gan** [Solaris-Skunk-Werks/solarisskunkwerks#226]
I don't know if it is because the equipment files seem to have changed from .dat to .json but in the SSW application Plasma Rifle and Plasma Cannon (as well as my custom equipment which is based on the Plasma Rifle) all show a being Ammo 0 and 0.0 Tons. Although when you add the ammo to the mech it does subtract 1 ton from the Free Tons available on the mech.
EDIT: Turns out its not just the Plasma weapons, it's actually every type of ammunition.

**Comment by WEKarnesky** [comment]
Few things before anything can be done.

1. Test on the latest release, which is 7.5
2. Ensure that you properly updated your datafiles, as 7.4 does have breaking changes to the way datafiles are written. See  Docs/CustomEquipment.MD for full details
3. Test Plasma Rifle/Cannon with stock files, and ensure it is working properly.  If it is not report back with specific details.
4. Then try adding your custom equipment and ensure that they are properly formatted.

**Comment by S2000Gan** [comment]
I have only modified my 7.4.1
I tried it on 7.4 which I have not modified at all and am seeing the same issue.
I also double checked 7.3 and 7.3.20200413 neither of which I have modified and it is working on both of those. 
I will check 7.5 which I did not realize was up.

**Comment by S2000Gan** [comment]
Just checked 7.5 still seeing Ammo 0 and Tonnage 0.0 under the Plasma Rifle and Plasma Cannon Ammo

**Comment by S2000Gan** [comment]
![image](https://user-images.githubusercontent.com/5659865/103076237-1ed0d680-4582-11eb-84f8-5d5a14fd0013.png)

**Comment by Maelwys** [comment]
Its not just Plasma cannon and plasma Rifle ammo, its all ammo. Not sure why, but when you add a new weapon and go down to Ammunition and select it on the left side, it shows 0 ammo count and 0 tonnage and 0 cost.

Once you add it to the unit and select it on the right side, those values are fine.

Happens in 7.6-f0a3e9298
Happens in 7.4

But doesn't seem to happen in 7.3.20200820, so its relatively new.

Its doing it in SAW as well.

Not sure what's been done recently that would affect it like that, except for maybe the ammo count for SAW to determine how many crit slots are used up, but not sure why that would affect what's being affected.

But its a systemic error, not just the plasma rifle/cannon.

**Comment by S2000Gan** [comment]
> Its not just Plasma cannon and plasma Rifle ammo, its all ammo. Not sure why, but when you add a new weapon and go down to Ammunition and select it on the left side, it shows 0 ammo count and 0 tonnage and 0 cost.
> But its a systemic error, not just the plasma rifle/cannon.

Oh! xD I didnt even notice!
The mech I am currently working on doesn't use any other ammo and I didn't think to check the more common ammo using weapons!
