### ISSUE TITLE
Meta: Incorrect Battle Value Calculations

### ISSUE THREAD

**Issue by WEKarnesky** [Solaris-Skunk-Werks/solarisskunkwerks#23]
Battle values for some equipment are incorrect.  Confirm and/or fix the BV for each item

- [x] iATMs and Streak LRMs
- [x] AES
- [x] composite structure
- [x] talons
- [x] chameleon LPS
- [x] null-sig
- [x] void-sig
- [x] Drone OS (#3)

**Comment by Algebro7** [comment]
LPS and null-sig fixed by 4087b09, which fixed the Cephalus C bv calculation. Void-sig's heat efficiency is fixed but it needs the defensive BV adjustment still.

**Comment by Algebro7** [comment]
@WEKarnesky for testing talons:

[SSW_0.7-Experimental.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3408181/SSW_0.7-Experimental.zip)

**Comment by WEKarnesky** [comment]
The stats are unchanged.
* Turkina X **MATCH** at 3,056 Vs MML's 3,056 and MUL's 3,056.
* Turkina U ***NOT MATCH*** at 2,520 (us) vs MML's 2,478 and MUL's 2,520
* Pariah (Septicemia) US ***NOT MATCH*** at 2,298 (us) vs MML's 2308 and MUL's 2,298

Turkina X has the following equipment:
* ECM Suite
* Medium Pulse Laser
* LRM-20
* Talons

The Turkina U has the following equipment:
* Active Probe
* Cargo, Liquid (1.0 tons)
* LRM-15
* ATM-9
* ER Small Laser
* HarJel
* Coolant Pod
* Talons
* Targeting Computer

The Pariah (Septicemia) US has the following equipment:
* ER Medium Laser
* ER Small Laser
* ER PPC
* Talons
* ECM Suite
* Spot Welder
* Cargo, Liquid (2.0 tons)

The only common thing that isn't in the Turkina X but are in the other two, is the Liquid Cargo container.  I don't know if that is in the source, but I'd check it before the talons.

**Comment by Algebro7** [comment]
Marking talons as correct--we've figured out that the talon mechs that don't align with MML is due to issues and limitations in MML (lack of coolant pod support, incomplete loadout for the Turkina, lack of heat modifier for spot welders)

**Comment by Algebro7** [comment]
Closing this issue now that all the initial items have been accounted for. Please re-open if anyone notices any other incorrect BV calculations for specific items or equipment.
