### ISSUE TITLE
Does not recognize ECM system is installed

### ISSUE THREAD

**Issue by ZPointZ** [Solaris-Skunk-Werks/solarisskunkwerks#230]
Hi there, great program first of all.

I've created a 'Mech that doesn't want to save on 0.7.4 because SSW doesn't recognize the Guardian ECM that's been installed. I'm using Stealth Armor, which may have something to do with it. Turning auto-add ECM on or off doesn't seem to matter.
![error](https://user-images.githubusercontent.com/73061772/108597631-f53afc80-73c4-11eb-9ca9-7be64fe7fcf2.png)

**Comment by Notsonoble** [comment]
This was fixed in 0.7.4.1, 7.5 is also stable at this point. https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/releases. Is there a reason you're on 0.7.4?

**Comment by ZPointZ** [comment]
i checked the SSW website but didn't think to see if there was a newer version here. obvious in hindsight. not to worry, i'll get the latest from here from now on.

**Comment by Notsonoble** [comment]
As long as it wasn't a specific reason, then no worries.
