### ISSUE TITLE
TSM Error

### ISSUE THREAD

**Issue by KingKonan** [Solaris-Skunk-Werks/solarisskunkwerks#242]
I don't know if this is system-wide or just on the BL-10-KNT (Ross) but the TSM speed shown on the sheet is incorrect.  The sheet shows Walking 4 (5) and Running 6 (8) which should be Walking 4 (6) and Running 6 (9) per the TSM rules of adding 2 to the walking speed of the mech with the system heated up and working . 

Triple Strength Myomer (aka TSM) is bulkier and also more expensive than standard myomer. It can be used in the "muscles" of BattleMechs instead of standard myomer, and delivers significantly improved performance when the 'Mech has hit a certain heat threshold (in the CBT game, activate at a heat level of 9+).[1] Under these conditions the 'Mech will move faster (add 2 to the normal walk speed, then multiply that speed by 1.5 to get the new run speed, rounding up) and deal more damage with physical attacks (double damage for applicable attack types, such as punching, kicking, and use of clubs, along with double lifting/throwing capacity).[2] 

Actually it looks like you might have a system wide error.  The Cudgel CDG-2a shows 5(6)/8(9)/0, the Ostsol OTL-9R shows 3(4)/5(6)/0 and the Ti Ts'ang TSG-9C shows 6(&)/9(11)/0

**Comment by WEKarnesky** [comment]
This is correct behavior.

You are correct that TSM adds 2 to movement, however you are missing that to activate TSM they must be suffering from a heat-based movement penalty of at least 1.  As such, the notation of 4(5) takes into account that penalty and is correct.

To cement that further, BL-10-KNT Black Knight Ross is from Starter Book Sword and Dragon, and you can see they follow the same notational system for the TSM movement increase

![image](https://user-images.githubusercontent.com/8506084/113207616-ab480080-9225-11eb-95c5-c52d2a74c7b6.png)

**Comment by KingKonan** [comment]
Ahhhh, interesting.  Hadn't thought about you already taking that into consideration and putting it on the sheet.  
Thanks for the mail.  
Mike 
    On Wednesday, March 31, 2021, 10:34:09 PM GMT+2, William E. Karnesky ***@***.***> wrote:  
 
 


This is correct behavior.

You are correct that TSM adds 2 to movement, however you are missing that to activate TSM they must be suffering from a heat-based movement penalty of at least 1. As such, the notation of 4(5) takes into account that penalty and is correct.

To cement that further, BL-10-KNT Black Knight Ross is from Starter Book Sword and Dragon, and you can see they follow the same notational system for the TSM movement increase
