### ISSUE TITLE
SRM2 IOS

### ISSUE THREAD

**Issue by VincentDegrassa** [Solaris-Skunk-Werks/solarisskunkwerks#245]
The Clan SRM2 (iOS) weighs too much.  Its list in SSW as .5t when it should be .25t

First noticed when trying to build the Crossbow T from il Clan Rec Guid Vol 17

**Comment by WEKarnesky** [comment]
Can you give page references or errata to support this?  It is possible that we are correct. Combined TacOps page 326 says 

> Improved One-Shot Missile Launchers weigh 0.5 tons less than their standard equivalents, to a minimum of 0.5 tons

It is also possible that something changed, but I am not aware of it and don't have the time to dig into it right now.

I would appreciate it if you or another can provide sources regarding this change.

In the interim, most weapons are in `Data/Equipment/weapons.json` and you can directly alter the weight of the weapons in that file.

**Comment by VincentDegrassa** [comment]
Tactical Operations -Advanced Units and Equipment, pg 138

Missile Launchers: All of the Missile Launchers described here may be mounted in accordance with the unit’s standard construction rules. Improved One-Shot Missile Launchers weigh 0.5 tons less than their standard equivalents, to a minimum of 0.5 tons (0.25 tons for Clan-made systems). ProtoMechs mounting a permitted missile system may install ammunition by the volley rather than by the ton (to find the per-volley weight, divide 1,000 by the weapon’s listed ammo per-ton value for a single tube; then multiply that by the number of missiles in the volley to find the kilogram weight of a single volley, rounded up to the nearest whole kg). Regardless of the number of tubes in a volley, a ProtoMech need only assign a single weapon slot to the launcher.

**Comment by WEKarnesky** [comment]
huh.  I wonder whenthat changed.

**Comment by WEKarnesky** [comment]
Hotfix pushed.
