### ISSUE TITLE
Void sig. component key in SSW mtf output may be peculiar

### ISSUE THREAD

**Issue by IsaBison** [Solaris-Skunk-Werks/solarisskunkwerks#253]
Flechs Sheets encountered an .mtf from SSW with `VoidSignatureSystem` — but the only key I had was `mech void signature system` (case insensitive). 

Not sure if `VoidSignatureSystem` key is very old or very new but I wanted to note it somewhere public in the event I don't get to looking in on it myself!

**Comment by gblouin** [comment]
I dug in and found the setup for the Void Sig in sswlib/src/main/java/components/Mech.java and it does set the MMName as VoidSignatureSystem which is what would be output to the MTF file.  Are you reporting that this name is incorrect and should be something else?  If so, what should it be?

**Comment by IanBellomy** [comment]
Apologies, just tested and this is non-problem. 

MMLab currently uses the key `Mek Void Signature System` but can correctly import files using the key SSW uses (`VoidSignatureSystem`). I'm assuming `VoidSignatureSystem` is just an old key.

**Comment by IsaBison** [comment]
Apologies, just tested and this is non-problem.

MMLab currently uses the key `Mek Void Signature System` but can correctly import files using the key SSW uses (`VoidSignatureSystem`). I'm assuming `VoidSignatureSystem` is just an old key.
