### ISSUE TITLE
Pile driver key in mtf output may be peculiar

### ISSUE THREAD

**Issue by IsaBison** [Solaris-Skunk-Werks/solarisskunkwerks#254]
Flechs Sheets encountered an .mtf from SSW with `HeavyDutyPile-Driver` — but the only key I had was `pile driver` (case insensitive). 

Not sure if `HeavyDutyPile-Driver` key is very old or very new but I wanted to note it somewhere public in the event I don't get to looking in on it myself!

**Comment by gblouin** [comment]
It sounds like we just have the wrong MMName listed in our data.  This is what I found in the physicals.json file.

  "Heavy Duty Pile-Driver": {
    "ActualName": "Heavy Duty Pile-Driver",
    "CritName": "Heavy Duty Pile-Driver",
    "MegaMekName": "HeavyDutyPile-Driver",
    "LookupName": "Heavy Duty Pile-Driver",
    "ChatName": "HDPD",

Does that sound right?

**Comment by Maelwys** [comment]
Looks like it should just be "Pile Driver"
