### ISSUE TITLE
Superheavy Vehicle issue

### ISSUE THREAD

**Issue by CampaignAnon** [Solaris-Skunk-Werks/solarisskunkwerks#26]
In the 6.83 and current .7 versions of SSW, it's possible to create and save Superheavy Vehicles. Attempting to load the file however, returns a popup error and kicks you back to the unit selection window. If I can get it to attach, I've also got one of the units that causes the error.

![Superheavy vehicle load](https://user-images.githubusercontent.com/48396292/61508807-2feede80-a9b1-11e9-8771-ad63265bf374.png)

**Comment by CampaignAnon** [comment]
[Mecklenberg Hover Battle Tank.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3409411/Mecklenberg.Hover.Battle.Tank.zip)
Here's the file itself.

**Comment by Algebro7** [comment]
I can't recreate this issue in the latest dev build. Can you try this build and see if it still happens to you?

[SSW_0.7-Experimental.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3413907/SSW_0.7-Experimental.zip)

**Comment by CampaignAnon** [comment]
Yes, I just tried it in the newest build. Created the exact same tank, and saved it. Attached is a screencap of each window from SAW. Also note that neither the Hovercraft or Displacement Superheavy Options have the side armor properly allocated, with the sides becoming 2 locations each. I just noticed that remaking it.

**Comment by Algebro7** [comment]
@CampaignAnon can you test with this build? I am able to create, save, and load super heavy hovers with it but I'm not 100% sure about the armor/equipment values.

[SSW_0.7-Experimental.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3417886/SSW_0.7-Experimental.zip)

**Comment by WEKarnesky** [comment]
Super Heavy Hover now works, The Super heavy Displacement has the same issue.  want the same ticket since it's related, or a separate ticket?

**Comment by Algebro7** [comment]
Thanks! Can you test this build to make sure the Super Heavy Displacement works (and that the super heavy hover still works)?

[SSW_0.7-Experimental.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3427686/SSW_0.7-Experimental.zip)

**Comment by CampaignAnon** [comment]
Might as well keep the same ticket up since they're related. I'll try the new version later.

**Comment by Algebro7** [comment]
Can anyone confirm if this is fixed for super heavy displacements and super heavy hovers?

**Comment by CampaignAnon** [comment]
Super Heavy hover vehicles work, while super heavy displacement vehicles suffer the same as they did before.

**Comment by njfox** [comment]
Did you try [this build](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3427686/SSW_0.7-Experimental.zip)?

**Comment by Algebro7** [comment]
Oops, can you try [this](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3427686/SSW_0.7-Experimental.zip)?

**Comment by CampaignAnon** [comment]
Looks like that solved it, yes. Thanks.
