### ISSUE TITLE
Null Pointer Exception in frmMain.BuildChassisSelector when loading the Snow Fox

### ISSUE THREAD

**Issue by Algebro7** [Solaris-Skunk-Werks/solarisskunkwerks#27]
Our version of SSW throws a NullPointerException when loading the Snow Fox from disk. It's hard to catch the right error, but it appears to be in `frmMain.BuildChassisSelctor()`:
```
    private void BuildChassisSelector() {
        // builds the structure selection box
        ArrayList list = new ArrayList();

        // get the structure states and, for each that matches our criteria, add it
        // to the selector list
        ifState[] check = CurMech.GetIntStruc().GetStates( CurMech.IsQuad() );
        for( int i = 0; i < check.length; i++ ) {
            if( CommonTools.IsAllowed( check[i].GetAvailability(), CurMech ) ) {
                list.add( BuildLookupName( check[i] ) );
            }
        }
```
The issue seems to be that `check.length` == 12, but the last 2 elements are null, which causes the exception when accessing `check[10]`. I just tested with 0.6.83 and there is no error, so we need to dig into `CurMech.GetIntStruc().GetStates( CurMech.IsQuad() )` to figure out why it's returning two extra null elements. I'm guessing there might be differences in our version of sswlib due to partially implemented features.

To Reproduce:
1. Open SSW
2. Click Open
3. Select Snow Fox

An empty dialog will appear, indicating the null pointer exception.

**Comment by WEKarnesky** [comment]
Seems Fixed in #31
