### ISSUE TITLE
Medium Shield should not cause Jump speed to show as (0)

### ISSUE THREAD

**Issue by S2000Gan** [Solaris-Skunk-Werks/solarisskunkwerks#305]
I just opened up a 55ton mech that has a medium shield and 5 jump jets and under the movement section of the basic setup page it shows as having 0 jump. ONLY the large shield prevents jumping! 
When you look at the print preview it shows as having a jumping speed of 5 (0).
Interestingly, I have a pdf of the same mech from SSW 0.7.3 and it does not have this problem.

**Comment by TonicArtos** [comment]
Physicals.json is missing 
`      "CanJump": true,`
for modifiers on medium shield

**Comment by TonicArtos** [comment]
I just noticed that shield -1MP does not stack at the moment either, nor is applied to jump MP ([shield movement penalty questions answered](https://bg.battletech.com/forums/tactical-operations/(answered)-mp-reduction-for-shields/)). I will create a new issue for this.
