### ISSUE TITLE
SAW - Sponson Turrets do not work correctly.

### ISSUE THREAD

**Issue by CampaignAnon** [Solaris-Skunk-Werks/solarisskunkwerks#39]
Currently under the most recent revision of SAW, sponson turrets are not required to allocate the 10% mass fraction of all weapons in each sponson, nor are the turrets showing up in a vehicle's statline. Sponson turrets also do not affect a vehicle's BV, when they should. Additionally per TacOps rules, Sponson Turrets are able to be mounted in addition to a vehicle's regular turret, not in place of.

**Comment by Algebro7** [comment]
Can anyone test Sponson turret functionality in this build? This required a complete implementation and so it's likely full of bugs that I've missed. Thanks!

[SSW_Sponson.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/4344558/SSW_Sponson.zip)

Note: I've moved Sponson turrets to the Experimental Equipment section from the turret selector. Set rules to experimental, then check the Sponson Turret box, then assign equipment to each side in the equipment tab.

**Comment by Algebro7** [comment]
This build fixes various printing/formatting issues with Tonnage and sponson-mounted weapons:

[SSW_Sponson_2.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/4344890/SSW_Sponson_2.zip)

**Comment by Algebro7** [comment]
And one more to fix left sponson items being listed twice....

[SSW_Sponson_3.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/4344929/SSW_Sponson_3.zip)

**Comment by Algebro7** [comment]
This build corrects a rounding error between left and right sponson turrets--they're now added together before applying the fraction and rounding. This is applied to the cost calculations as well.

[SSW_Sponson_4.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/4345779/SSW_Sponson_4.zip)

**Comment by Algebro7** [comment]
Sponsons are now fully implemented with #119.
