### ISSUE TITLE
Shield Printing overlap issue

### ISSUE THREAD

**Issue by bcompter** [Solaris-Skunk-Werks/solarisskunkwerks#4]
When a 'mech has a shield, the armor points text overlaps the shield image.

**Comment by bcompter** [comment]
![shield_bug](https://cloud.githubusercontent.com/assets/6876373/13006948/87ff9dd6-d15a-11e5-90fc-0be22b0ffb3f.png)

**Comment by WEKarnesky** [comment]
resolved in #58
