### ISSUE TITLE
Primitive Battlemechs should be able to equip all armor types

### ISSUE THREAD

**Issue by Algebro7** [Solaris-Skunk-Werks/solarisskunkwerks#40]
According to VhenRa on Discord, primitive battlemechs should have no restrictions on the type of armor they can equip. Currently, they are restricted only to primitive armor.

**Comment by Algebro7** [comment]
I believe this problem is fixed in the build below:

[SSW_0.7-Experimental.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3504133/SSW_0.7-Experimental.zip)

**Comment by Algebro7** [comment]
#46 should fix this, although we need to watch out for bugs in the UI when switching eras with primitive mechs selected. As of this PR, switching to DA breaks the UI, but that happens to regular mechs as well because the DA availability codes have not been fully implemented for all components such as engines.

**Comment by WEKarnesky** [comment]
Merged
