### ISSUE TITLE
When choose "Print Preview" and "Printing" does not appear image mech

### ISSUE THREAD

**Issue by Latinoz** [Solaris-Skunk-Werks/solarisskunkwerks#42]
When choose "Print Preview" and "Printing" does not appear. 
And selecting a mech picture is not displayed
It is also not printed.
The problem is still with version 0.7

**Screenshots**

![ssw_scr_1](https://user-images.githubusercontent.com/16256418/64478375-5ca0c480-d1b0-11e9-8c27-1ccbf8d60418.PNG)
![ssw_scr_2](https://user-images.githubusercontent.com/16256418/64478374-5ca0c480-d1b0-11e9-8157-c55c4c7443b4.PNG)

**Comment by Algebro7** [comment]
This appears to be some sort of bug with the "Choose TRO Pic" button, although I haven't been able to figure out what's wrong while debugging it. As a workaround until I can figure it out, you can choose the image in the fluff tab of SSW and then it will show up on the record sheet.

**Comment by Algebro7** [comment]
This should be fixed by #125. Please reopen if you notice any other issues.
