### ISSUE TITLE
iATM-6 Inferno Ammo Improperly Named

### ISSUE THREAD

**Issue by brstrommen** [Solaris-Skunk-Werks/solarisskunkwerks#45]
**Describe the bug**
The iATM ammo types are suffixed with -6 to represent the 6-missile volleys the weapon fires in. When adding the ammo to the mech loadout, the improved inferno warhead ammo type has the wrong name, @IIW-3 instead of @IIW-6.  Its MM Name is correct, with CLIIW6 Ammo, and its other attributes (like amount of ammo per bin) are also correct.  The 3, 9, and 12-size versions of this weapon and ammo are correct.

**To Reproduce**
0. Launch SSW/create new mech
1. Enable experimental tech
2. Set techbase to Clan
3. Go to Equipment tab
4. Add an iATM-6 from the missile submenu
5. Go to ammunition submenu
6. Observe the improved inferno warhead missile ammo is named @ IIW-3 instead of @ IIW-6

**Expected behavior**
The name for the iATM inferno ammo should be @ IIW-6

**Comment by Algebro7** [comment]
Pretty sure this needs to be fixed in the Equipment.ods spreadsheet and re-imported:

![Screenshot_20190923_115519](https://user-images.githubusercontent.com/5447759/65441893-b8a75200-de1a-11e9-8af9-575f75351e04.png)
