### ISSUE TITLE
BFB can't load mech files correct if SSW was not ran first

### ISSUE THREAD

**Issue by KaydenMiller** [Solaris-Skunk-Werks/solarisskunkwerks#54]
**Describe the bug**
BFB can't load mech files correctly if SSW has never been ran to populate the preferences, resulting in record sheets not showing up when printing.

**To Reproduce**
1. Go to registry and find file under HKEY_CURRENT_USER\Software\JavaSoft\Prefs\com\
2. Delete all registry files associated with BFB or SSW
3. Attempt to print a record sheet from BFB before launching SSW

**Expected behavior**
Should be able to display record sheets for associated mechs.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 10.0.18362 Build 18362

**Additional context**
There is some more context in the discord general chat for 9/30/2019.

**Comment by KaydenMiller** [comment]
This issue might be related to #42

**Comment by Algebro7** [comment]
This should be fixed with #124. Please reopen if you notice any other issues.
