### ISSUE TITLE
SAW is "Remembering" Turrets

### ISSUE THREAD

**Issue by Maelwys** [Solaris-Skunk-Werks/solarisskunkwerks#59]
I was playing around with a Dev copy of the SSW Master list in SAW and noticed something odd when I was trying to correct some dates that had been changed in the MUL.

Say I have two designs. Design A has a Turret, Design B does not.

If I just load B first, then its fine, nothing is wrong (or if I click the "new vehicle" button, which clears everything out and sets it to no Turret, and then load B, it loads fine)
 
However, if I load A then B, B will suddenly have a turret added in (nothing assigned to it, not armor, its just there)

So it seems SAW is remembering the turret (or not loading a no turret or something).

This is version 6.82.1, btw.

**Comment by Algebro7** [comment]
Closed via #126
