### ISSUE TITLE
IO Off era equipment

### ISSUE THREAD

**Issue by Notsonoble** [Solaris-Skunk-Werks/solarisskunkwerks#63]
Clan Prototype and Improved equipment, later IS and clan equipment.

MML has implemented some of this, but with big typos. It's mostly a "would be nice" feature.

**Comment by WEKarnesky** [comment]
I think this is just a duplicate of #24, can you confirm how it's different?

**Comment by Notsonoble** [comment]
It is, I just missed #24 when looking for it.

**Comment by WEKarnesky** [comment]
Okay, no problem.  Please feel free to add more information or note anything missing from #24.  If you want, most of the requests are as simple as editing the excel sheet `Docs/Equipment.ods` with the correct values.
