### ISSUE TITLE
BV Calculation doesn't match MML

### ISSUE THREAD

**Issue by WEKarnesky** [Solaris-Skunk-Werks/solarisskunkwerks#70]
**Describe the bug**
There is a possible BV calculation error centering around Void Sig.  This zip contains two custom mechs.

The Tarnkappe mech seems to match in both SSW and MML, however the Yukionna BHM-3X does not.  

The deviation seems to be:

* MML uses a Defensive Movement Factor of 1.3
* SSW uses a Defensive Speed Factor of 1.5

[customMechs.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3703224/customMechs.zip)

**Comment by WEKarnesky** [comment]
The following is the BV breakdown produced by SSW 0.7.0

     Mech Name:   Yukionna BHM-3X                           Tonnage:    100
     Rules Level: Experimental Tech                         Total Cost: 31,808,000
     Tech Base:   Inner Sphere                              Total BV:   2,683
     
     Item                                            DefBV     OffBV             Cost
     Internal Structure - Standard                  114         0           40,000.00
     Engine - XL Fusion Engine                        0         0        8,000,000.00
     Gyro - Compact Gyro                             50         0        1,800,000.00
     Cockpit - Standard                               0         0          450,000.00
     Heat Sinks - Double Heat Sink                    0         0           84,000.00
     Musculature - Standard                           0       100          200,000.00
     Actuators                                        0         0          100,000.00
     Armor - Standard Armor                         720         0          180,000.00
     
     Gauss Rifle                                         0       320       300,000.00
     Gauss Rifle                                         0       320       300,000.00
     ER PPC                                              0       229       300,000.00
     Angel ECM                                         100         0       750,000.00
     Bloodhound Active Probe                            25         0       500,000.00
     @ Gauss Rifle                                       0        40        20,000.00
     @ Gauss Rifle                                       0        40        20,000.00
     @ Gauss Rifle                                       0        40        20,000.00
     @ Gauss Rifle                                       0        40        20,000.00
     @ Gauss Rifle                                       0        40        20,000.00
     Command Console                                     0         0       500,000.00
     Void Signature System                               0         0     2,000,000.00
     CASE II                                             0         0       175,000.00
     CASE II                                             0         0       175,000.00
     
     Cost Multiplier                                                            2.000
     Dry Cost                                                              31,708,000
     Total Cost                                                            31,808,000
     
     
     Defensive BV Calculation Breakdown
     (Note: BV Calculations include defensive BV for armored components.)
     ________________________________________________________________________________
     Total Armor Factor (288) * Armor Type Modifier (1.0) * 2.5                720.00
     Total Structure Points (152) * Structure Type Modifier (1.0)
         * Engine Type Modifier (0.5) * 1.5                                    114.00
     Mech Tonnage (100) * Gyro Type Modifer (0.5)                               50.00
     Total Defensive BV of all Equipment                                       125.00
     Excessive Ammunition Penalty                                                0.00
     Explosive Ammunition Penalty                                                0.00
     Explosive Item Penalty                                                      0.00
     Subtotal                                                                1,009.00
     Defensive Speed Factor Breakdown:
         Maximum Ground Movement Modifier: 1.20
         Maximum Jump Movement Modifier:   0.00
         Defensive Speed Factor Bonus from Equipment: 0.30
         Minimum Defensive Speed Factor:   0.00
         (Max of Run or Jump) + DSF Bonus = 1.50
     Total DBV (Subtotal * Defensive Speed Factor (1.50))                    1,513.50
     
     
     Offensive BV Calculation Breakdown
     ________________________________________________________________________________
     Heat Efficiency (6 + 28 (Dissipation) - 2 (Movement Heat) - 10 (Void-Signature System)) = 22.0
     Adjusted Weapon BV Total WBV                                              869.00
         -> Gauss Rifle                                                        320.00
         -> Gauss Rifle                                                        320.00
         -> ER PPC                                                             229.00
     Non-Heat Equipment Total NHBV                                             200.00
         -> Angel ECM                                                            0.00
         -> Bloodhound Active Probe                                              0.00
         -> @ Gauss Rifle                                                       40.00
         -> @ Gauss Rifle                                                       40.00
         -> @ Gauss Rifle                                                       40.00
         -> @ Gauss Rifle                                                       40.00
         -> @ Gauss Rifle                                                       40.00
     Excessive Ammunition Penalty                                                0.00
     Mech Tonnage Bonus                                                        100.00
     Subtotal (WBV + NHBV - Excessive Ammo + Tonnage Bonus)                  1,169.00
     Offensive Speed Factor Breakdown:
         Adjusted Running MP (5) + ( Adjusted Jumping MP (0) / 2 ) - 5 = 0.00
         0.00 / 10 + 1 = 1.000
         1.00 ^ 1.2 = 1.0 (rounded off to two digits)
     Total OBV (Subtotal * Offensive Speed Factor (1.0))                     1,169.00
     
     
     Total Battle Value (DBV + OBV, round off)                                  2,683

**Comment by WEKarnesky** [comment]
Here is the BV output of MML 0.46.0



    Battle Value Calculations For Yukionna BHM-3X
     Defensive Battle Rating Calculation: 
    Total Armor HD (9) x 1.0
    9.0
    Total Armor CT (61) x 1.0
    61.0
    Total Armor RT (41) x 1.0
    41.0
    Total Armor LT (41) x 1.0
    41.0
    Total Armor RA (32) x 1.0
    32.0
    Total Armor LA (32) x 1.0
    32.0
    Total Armor RL (36) x 1.0
    36.0
    Total Armor LL (36) x 1.0
    36.0
    Total modified armor BV x 2.5
    = 720.0
    Total I.S. Points x IS Multipler x 1.5 x Engine Multipler
    152 x 1.0 x 1.5 x 0.5
    = 114.0
    Weight x Gyro Multipler
    100.0 x 0.5
    = 50.0
    Defensive Equipment:
    
    
    Bloodhound Active Probe
    
    +25.0
    Angel ECM Suite
    
    +100.0
    Total BV of all Defensive Equipment
    
    = 125.0
    Explosive Weapons/Equipment Penalty
    
    = -0.0
    
    
    -------------
    
    
    1009.0
    Run MP
    
    5
    Target Movement Modifier For Run
    
    2
    Target Movement Modifier For Jumping
    
    0
    Target Movement Modifier For UMUs
    
    0
    Target Movement Modifier
    
    2.0
    Void Sig
    
    3
    Multiply by Defensive Movement Factor of
    1.3
    x 1.3
    
    
    -------------
    Defensive Battle Value
    
    = 1311.7
    
    
    
    Offensive Battle Rating Calculation:
    
    
    Base Heat Efficiency - Run Heat - Void-signature system Heat
    34 - 2
    = 22
    Unmodified Weapon BV:
    
    
    Gauss Rifle
    
    320.0
    Gauss Rifle
    
    320.0
    ER PPC
    
    229.0
    
    
    -------------
    Unmodified Front BV:
    
    869.0
    Unmodfied Rear BV:
    
    0.0
    Unmodfied Turret BV:
    
    0.0
    Total Unmodfied BV:
    
    869.0
    Unmodified Front non-arm BV:
    
    229.0
    Unmodfied Rear non-arm BV:
    
    0.0
    Weapon Heat:
    
    
    Gauss Rifle
    
    + 1.0
    Gauss Rifle
    
    + 1.0
    ER PPC
    
    + 15.0
    
    
    -------------
    Total Heat:
    
    = 17.0
    Weapons with no heat at full BV:
    Heat Modified Weapons BV:
    
    
    Gauss Rifle
    
    320.0
    Gauss Rifle
    
    320.0
    ER PPC
    
    229.0
    
    
    -------------
    Total Weapons BV Adjusted For Heat:
    
    869.0
    Misc Offensive Equipment:
    
    
    Total Misc Offensive Equipment BV:
    
    0.0
    Total Ammo BV:
    
    200.0
    Add weight
    
    +100.0
    Final Speed Factor:
    
    1.0
    Weapons BV * Speed Factor
    1169.0 * 1.0
    = 1169.0
    Offensive BV + Defensive BV
    1311.7 + 1169.0
    = 2480.7
    Total BV * Cockpit Modifier
    2480.7 * 1.0
    = 2481.0
    
    
    -------------
    Final BV
    
    2481.0

**Comment by Algebro7** [comment]
I think this issue is fixed with this build, can you test @Maelwys?

[SSW_0.7.0.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3705316/SSW_0.7.0.zip)

**Comment by WEKarnesky** [comment]
[The fix has been published](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/releases/tag/v0.7.1)
