### ISSUE TITLE
Should clean up the two Docs folders

### ISSUE THREAD

**Issue by mrpopogod** [Solaris-Skunk-Werks/solarisskunkwerks#79]
The base repository has both a Docs and a docs folder.  This collides on a Windows file system (not case sensitive), which causes the paths to be merged and then a collision exists between a handful of files; two licenses, FAQ.txt, and HTML_Tags.txt.  Spot checking FAQ and HTML_Tags shows the files as identical.  These should probably be merged into a single directory to avoid confusion.

**Comment by WEKarnesky** [comment]
@Algebro7 I'm on a windows system and didn't notice this, you should be able to do this, since you are not.

**Comment by WEKarnesky** [comment]
git is funky about empty directories so it's likely that empty directory will still be in your local tree, but a fresh pull to empty should no longer have it.
