### ISSUE TITLE
Dark Age Availability

### ISSUE THREAD

**Issue by Maelwys** [Solaris-Skunk-Werks/solarisskunkwerks#8]
The Dark Age availability codes for equipment needs to be implemented, and put into use (I think right now it just uses the codes from Clan era as default).

Details are in IO.

**Comment by bcompter** [comment]
This is at least partially implemented in the version I got from SkyHigh.  I'm sure there are a few errors so I'll need help when it comes time to release stuff.

**Comment by Maelwys** [comment]
Yeah, I'm not sure how much its actually taking, and how much is just a default setting (I think currently all DA designs default to a rating of A).

On the plus side, the excel sheet has already been adjusted so there's a column for the DA data, and I'm pretty sure that means the compiler had been adjusted too.

Oh god. I just realized we have two spreadsheets of equipment with different dates...

**Comment by Maelwys** [comment]
I guess the first bit would be to define what the dark age is, so the first little bit would be to set the Clan Invasion to end in 3130 and Dark Ages to start in 3131

**Comment by WEKarnesky** [comment]
Availability has not been updated from TRO: Prototypes or TRO:3145.

**Comment by WEKarnesky** [comment]
This PDF has all the updated availabilities:

[Tech_Advancement_3090_3145.pdf](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3418675/Tech_Advancement_3090_3145.pdf)

**Comment by Algebro7** [comment]
I've started working on adding the Dark Age availability codes. Can someone download the build below and test it for me? It should work properly in SSW (probably not SAW and BFB yet) for equipment that is stored in the .dat files (Weapons, equipment, etc. but not components like engines or chasses)

Thanks!
[SSW_0.7-Experimental.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3423857/SSW_0.7-Experimental.zip)

**Comment by Algebro7** [comment]
This issue is closed by #49. Thanks everyone for your help in researching these codes so we could implement them as accurately as possible!
