### ISSUE TITLE
Updated production Eras

### ISSUE THREAD

**Issue by Maelwys** [Solaris-Skunk-Werks/solarisskunkwerks#81]
SSW's production Eras are based on the various MUL Eras. Since the last time SSW was worked on, the Eras have been added to, and so SSW's need to be updated.

http://masterunitlist.info/Era/Index

Basically the Late Succession war needs to be broken up into Late Succession War - Lostech and Late Succession War - Renaissance, while Republic needs to be broken up into Early Republic and Late Republic.

**Comment by WEKarnesky** [comment]
[SSW_0.7.3.20200110 ALPHA 1.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/4048947/SSW_0.7.3.20200110.ALPHA.1.zip)

Please test this as much as you can to ensure it loads the trouble mechs correctly.

**Comment by WEKarnesky** [comment]
Implemented in dev version https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/releases/tag/0.7.3.20200113
