### ISSUE TITLE
MTF output incorrect with respect to Command Console. 

### ISSUE THREAD

**Issue by IanBellomy** [Solaris-Skunk-Werks/solarisskunkwerks#87]
MegaMek Lab notes a command console in an MTF by listing it as a cockpit type and then marking head slots 3 and 4 as "cockpit" (the command console is two crits). 

SSW's MTF output also notes the cockpit type like MML but then marks head slot 3 as cockpit and slot 4 as command console.

**Comment by WEKarnesky** [comment]
Will be fixed in the next nightly build.  No current ETA to go to the stable branch.
