### ISSUE TITLE
SSW half forgets about CASE II

### ISSUE THREAD

**Issue by Maelwys** [Solaris-Skunk-Werks/solarisskunkwerks#9]
When creating an OmniMech with CASE II as fixed equipment, SSW seems to "lose" the CASE II.

For instance, when creating the LI-O Vandal OmniMech (Which has CASE II in the RT as fixed equipment), the design should have 26.5 tons of pod space. And when you first create it, it does have 26.5 tons showing for pod space.

However, once you Lock the Chassis, the free weight jumps up to 27.5 tons. CASE II still shows up in the Criticals Tab, and the button for selecting it is greyed out. 

I suspect its also not being counted when it comes to BV calculations, but I'm not positive.

If I had to guess, it would be some sort of failure to load, but I'm not positive.

**Comment by Maelwys** [comment]
Yeah, I just checked, and its not counting towards BV calculations, so its not really there. Pretty sure its a failure to load (I seem to recall issues like this before).

**Comment by bcompter** [comment]
Nice one.  This one should be easy to figure out.

**Comment by bcompter** [comment]
I forgot that this probably impacts quad loadouts too...

**Comment by WEKarnesky** [comment]
Xotl has confirmed this is working properly
