### ISSUE TITLE
Bug: Widescreen mode for SSW removes Quirks tab

### ISSUE THREAD

**Issue by Xeno426** [Solaris-Skunk-Werks/solarisskunkwerks#90]
**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser How is this pertinent?
 - Version 0.7.0

**Describe the bug**
Widescreen version of the SSW window does not provide an entry for quirks.

**Expected behavior**
There should be a "quirks" tab under "Fluff".
![with quirks](https://user-images.githubusercontent.com/3220418/67127080-32ceba80-f1be-11e9-8909-2c80c7f01c94.png)

**Screenshots**
This is what the widescreen version currently shows.
![no quirks](https://user-images.githubusercontent.com/3220418/67126991-fbf8a480-f1bd-11e9-81d7-4e92e6fdae59.PNG)

**Comment by WEKarnesky** [comment]
## Good news:
This is released in the most recent dev release https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/releases/tag/0.7.3.20200113

## Bad News:
While implementing I learned that loading and saving quirks is not implemented in anything.  It will take a bit to get that part working, please file a ticket for that to keep us honest.
