### ISSUE TITLE
Drone OS Battle Value

### ISSUE THREAD

**Issue by Maelwys** [Solaris-Skunk-Werks/solarisskunkwerks#91]
According to the TacOps errata...

"All weapons on a unit equipped with a Drone Remote Operating System multiply their BVs by 0.8. Do not include ammunition when making these BV adjustments. In addition, multiply the final unit BV by 0.95. Do not apply any BV modifiers for cockpits."

SSW isn't doing this at the moment, so we need to add in a check for the Drone OS, then multiply any weapon BVs  by 0.8, remove any mods for the cockpit (like small or torso, but maybe not FCS) and then add in a final multiplication at the end.

**Comment by WEKarnesky** [comment]
Okay, It looks like we are including the final 0.95 multiplication already:

https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/blob/f10503f14a39ff0ceb02fb664aea345345b40e62/sswlib/src/main/java/components/Mech.java#L2365-L2370

Looking into the weapons calculations now.

**Comment by Maelwys** [comment]
Seems SSW is handling the calculations properly when the Mech is designed, but it is not loading it properly. Loading a mech, and then removing the Drone OS and adding it back will cause the calculations to work again.

**Comment by WEKarnesky** [comment]
Test this: 
[SSW_0.7.2-DroneOSFix.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3746129/SSW_0.7.2-DroneOSFix.zip)

**Comment by WEKarnesky** [comment]
loading now properly marks the drone OS as of commit https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/commit/14aa7c4b7fe1660d731550c4d6a9dd662acfe995 A hotfix release will go out relatively soon with this fix in it.
