### ISSUE TITLE
SAW is not adding Shielding Weight to Fission engines

### ISSUE THREAD

**Issue by Maelwys** [Solaris-Skunk-Werks/solarisskunkwerks#94]
Fission engines for Combat Vehicles are a TacOps rule, on page 306 and 307.

Like fusion engines, they require shielding which weighs 50% of their mass. SAW is not adding that in (though it is calculating rating and heat sinks right, as well as handling power amplifiers correctly)

**Comment by Algebro7** [comment]
Is SAW correctly adding shielding weight to fusion engines?

**Comment by Algebro7** [comment]
Closing as this should be fixed with #120. Please re-open if you notice any issues with Fission engine weights.
