### ISSUE TITLE
Error when opening SSW mechfile from version 06.83.1: setSelectedIndex: 9 out of bounds

### ISSUE THREAD

**Issue by Andai82** [Solaris-Skunk-Werks/solarisskunkwerks#96]
When i try to open some self designed mechs for the timelines 3085+ i got the error:

setSelectedIndex: 9 out of bounds

see screenshot and mechfile.

Version mechfile created: Sloaris Skunkwerks 06.83.1
https://www.file-upload.net/download-13759544/Error-SSW.zip.html

**Comment by WEKarnesky** [comment]
You likely need to change the production era and/or loadout_era to below 9.  8 is dark age currently.

Let me know if this solves your problem.

**Comment by Andai82** [comment]
Solves the problem, but really inconveniant changing every mech (with editor) built previously in SSW for DarkAge...no possibility changing it to 9?

**Comment by WEKarnesky** [comment]
No a bug so much as a different breakdown of eras.  we plan to revisit the listed eras later, but that will be further down the line.

You can use a tool like Notepad++ to to bulk edits of the files.
