### ISSUE TITLE
weapon: TSEMP (OS) missing

### ISSUE THREAD

**Issue by Andai82** [Solaris-Skunk-Werks/solarisskunkwerks#97]
When bulding mechs in dark age era and overall, the TSEMP (OS) seems to be missing.

**Comment by WEKarnesky** [comment]
It appears it's availability code is improperly E/XXXX when it should be E/XXXE.  This will be fixed in the next nightly release.

Until then, you should be able to use use era specific/all eras to build mechs using it.

**Comment by Andai82** [comment]
Works, thank you as i´m triingto make my mechs workto deliver you an all complete mech files pack until 3150 ^^

**Comment by WEKarnesky** [comment]
make sure you coordinate with @Maelwys, who is also working on adding in missing mechs

**Comment by Andai82** [comment]
Great, thank you, will do, maybe i can send him my files tomorrow, as i think i have covered apparantly 98% of all official mechs

**Comment by WEKarnesky** [comment]
fixed in commit 9eb59a8
