### ISSUE TITLE
Request to change how Prototype Double and Single Heat Sink dissipation is displayed in the Text TRO format

### ISSUE THREAD

**Issue by CampaignAnon** [Solaris-Skunk-Werks/solarisskunkwerks#98]
With the excellent addition of Freezers to SSW, there's a small issue in that with the default method that SSW outputs a mech's dissipation, you can't tell from the TRO entry exactly how many Freezers it has without looking to the crits. Currently, this means that for something like a Warhammer -6R, with 11 internal heat sinks and 7 external sinks, that the overall total for dissipation is presented as "18 (25)." I'd like to have the dissipation changed splitting the regular SHS and the freezers apart, so something like "11 + 7 (14) = 25", making it clear how many Freezers a mech is using.

**Comment by WEKarnesky** [comment]
This is now out in the latest nightly build.

https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/releases/tag/0.7.3.20191031
